import { Oswald } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const oswald = Oswald({ subsets: ["latin"] });

export const metadata = {
  title: "Your NEXT event",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${oswald.className} bg-[#D8D7D4] grid place-items-center p-10 `}>
        <nav className="flex gap-8 text-6xl p-5">
          <Link className="hover:text-[#DABD4C]" href="/">
            Home
          </Link>
          <Link className="hover:text-[#DABD4C]" href="/add-event">
            Add event
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
